### ISSUE TITLE
Logger: Follow wildcard topics

### ISSUE THREAD

**Issue by mitra42** [mitra42/frugal-iot#91]
The config file should be able to have a way to follow all nodes e.g. 
```
projects
  - name: Lotus Ponds
    nodes:
      - id: +
      - track:
        - humidity
        - temperature
```
Then it would subscribe to `dev/Lotus Ponds/+/humidity`  and `dev/Lotus Ponds/+/temperature` and record data for any nodes in that project publishing `temperature` or `humidity`
